### ISSUE TITLE
When setting config dynamically connections are not reused

### ISSUE THREAD

**Issue by mjclemente** [MatteoGioioso/serverless-pg#33]
First of all, thanks for the project! Really helpful for using PG with Lambda.

The README shows how to set the config dynamically, using `setConfig()`:

```
const handler = async(event, context) => {
    const {user, password} = await getCredentials('my-secret')
    client.setConfig({
      user, password
    })
    await client.connect();
    // ...rest of the code
}
```

The issue we experienced with this approach is that it actually resets the client each time, so you don't get to reuse the connections. This is because `setConfig()` [begins](https://github.com/MatteoGioioso/serverless-pg/blob/22bf4a4025e1d5b955f5d37a7f8936ae170257b9/src/index.js#L284) by setting the client to null: `this._client = null;`.

Workaround:

By removing the client reset at the start of `setConfig()`, we found that our lambda connections were reused, as expected.

**Comment by MatteoGioioso** [comment]
@mjclemente hey, thanks, let me check on this real quick =)

**Comment by MatteoGioioso** [comment]
@mjclemente Many thanks for spotting this bug! I have pushed a fix

**Comment by mjclemente** [comment]
@MatteoGioioso Thanks so much for the amazingly fast update, and for the really helpful project 🎉
