### ISSUE TITLE
Values set in config can be lost when configuration is dynamically updated

### ISSUE THREAD

**Issue by mjclemente** [MatteoGioioso/serverless-pg#35]
Again - thank you for this project. It's performed really well under load and we're very happy using it!

When configuring the connection dynamically, as in the example from the documentation, we've found that options like `debug` or `maxConnections` can be lost. So, given the following setup, the debug flag actually does not get applied:

```
const client = new ServerlessClient({
    host: process.env.DB_HOST,
    database: process.env.DB_NAME,
    port: process.env.DB_PORT,
    debug: true
});

const handler = async(event, context) => {
    const {user, password} = await getCredentials('my-secret')
    client.setConfig({
      user, password
    })
    await client.connect();
    // ...rest of the code
}
```
 
It appears that this is because some of the settings in `setConfig()`, like [the debug flag](https://github.com/MatteoGioioso/serverless-pg/blob/f23fc7bcefd53bcc8c83f2d1545c84a4fb6a5129/src/index.js#L345), are referencing the `config` object that's being passed in, instead of the merged config object; i.e. `this._config.debug`.

Workaround:
For now, we're setting options within the dynamic/async configuration, so we can be sure they're applied.

**Comment by MatteoGioioso** [comment]
Thanks once again for spotting another bug, I have pushed a fix

**Comment by mjclemente** [comment]
And again thank you got handling it so quickly! 💯

**Comment by MatteoGioioso** [comment]
No problem, let me know if you spot any other bug
