### ISSUE TITLE
Connections cleaning

### ISSUE THREAD

**Issue by AlexHramovich** [MatteoGioioso/serverless-pg#37]
Hey. Thanks for your library. It's great !

Could you please explain some details of clearing connections when connecting to db by connection string?
I think it doesn't work yet :)

I checked the code and found that the strategy requires a username and dbName from the config. But when we connect via connection string, the credentials are missing.

Best.

**Comment by MatteoGioioso** [comment]
Hello, could you please paste an example of what are trying to do?

If I have understood correctly you want to use connection string instead of providing multiple parameters?

**Comment by AlexHramovich** [comment]
Yes exactly

**Comment by AlexHramovich** [comment]
When I connect by user and password all is OK
```
db.setConfig({
        maxConnections: 10,
        user: process.env.DB_USER,
        host: process.env.DB_HOST,
        database: process.env.DB_NAME,
        password: process.env.DB_PASSWORD,
        port: process.env.DB_PORT,
    });
```

But when I connect via connectStr some services are not working, I think
```
db.setConfig({
        connectionString: process.env.CONNECTION_STRING,
        maxConnections: 10,
    });
```

**Comment by MatteoGioioso** [comment]
I see, let me push a fix during the weekend or on Monday

**Comment by MatteoGioioso** [comment]
hey, are you sure your connection string is correct?

I have tried this:

```
it("should be able to connect with connection string through setConfig", async function() {
      const client = new ServerlessClient({
        debug: true,
      });

      client.setConfig({
        connectionString: "postgresql://postgres:postgres@localhost:5433/postgres",
        maxConnections: 10,
      })

      await client.connect()
      await client.end()
    })

```

And it can connect

**Comment by AlexHramovich** [comment]
Yes you are right :)
But I meant something else

I will try to give you more details
See screenshot below

![Screenshot 2021-02-08 at 12 08 04](https://user-images.githubusercontent.com/26567520/107198654-71693380-6a06-11eb-821c-d8b2d17d764a.png)

I think it won't work when you connected via connection string

**Comment by MatteoGioioso** [comment]
Ah, I see now. Let me try to fix this.

**Comment by MatteoGioioso** [comment]
@AlexHramovich I have pushed a fix for this.
Please let me know if it solves it. If not I will reopen

**Comment by AlexHramovich** [comment]
Sorry for my late reply
Works correctly. Many thanks !
