### ISSUE TITLE
Installing the latest version of PG make connect never end

### ISSUE THREAD

**Issue by etienne-dldc** [MatteoGioioso/serverless-pg#38]
Hi 👋 

I had an issue where `await client.connect()` never ended with no error.
After some investigation I noticed that `serverless-postgres` uses the v7 of `pg` while I had the v8 installed on my project.
To solve this I've used yarn `resolution` field in `package.json` to force `serverless-postgres` to use v8 of `pg` :

```json
{
  "resolutions": {
    "pg": "8.5.1"
  }
}
```

This works but I'm wondering: Is there a reason for `serverless-postgres` not to use v8 if `pg` ?

In any case I think it would be nice to add a warning in the README about having 2 different versions of `pg`.

**Comment by MatteoGioioso** [comment]
Hello, 
No, there is no particular reason =)
I just forgot to upgrade the version of `pg`, but thanks for finding this out.

I will update to pg 8 in the next release.

**Comment by etienne-dldc** [comment]
Awesome ! Thanks 😃

**Comment by followbl** [comment]
holy moly @etienne-dldc thank you for posting this - was going crazy the last 24 hours figuring out why I couldn't make a connection.

@MatteoGioioso thanks for a great lib

**Comment by MatteoGioioso** [comment]
I have pushed a fix, please let me know if that works, if not I will reopen, thanks
