### ISSUE TITLE
Inserts with named fields result in a syntax error

### ISSUE THREAD

**Issue by SleeplessByte** [MatteoGioioso/serverless-pg#40]
I have no clue if this is me, or the library, or something else, but that's also because I haven't found a good way to debug this.

Given the following insert query on a table with at least these three columns:

```sql
EXPLAIN INSERT INTO entries (id, title, content) 
             VALUES (DEFAULT, ?, ?);
```

This yields a `syntax error at or near ","`.

Removing the column names and relying on the table column order:

```sql
EXPLAIN INSERT INTO entries
             VALUES (DEFAULT, ?, ?);
```

This yields a result.

I could it like this:

```javascript
db.query(
  'EXPLAIN INSERT INTO entries (id, title, content) VALUES (DEFAULT, ?, ?);',
  ['a', 'b']
)
```

1. Is there anything I can try to debug this?
2. Is this syntax somehow not supported?
3. Should I have done this differently? I see no INSERT examples in the readme.

**Comment by MatteoGioioso** [comment]
Hello, I will test this case, but two things:

1. Not sure question marks in parameterized query is valid Postgres syntax: (postgres docs)[https://www.postgresql.org/docs/current/sql-prepare.html], 
2. This is not a postgres driver, it is just a wrapper of the node-pg library and that library does not support that syntax: (node-pg issue)[https://github.com/brianc/node-postgres/issues/1100]

**Comment by SleeplessByte** [comment]
Thanks! 

It works when I use it without the table names, which is why I expected this to work. However, I will try this. I'm used to having to do $1, $2, $n manually anyway :).
