### ISSUE TITLE
Source code in v1.9.2 is different than the one in master branch

### ISSUE THREAD

**Issue by brapifra** [MatteoGioioso/serverless-pg#42]
[This line](https://github.com/MatteoGioioso/serverless-pg/blame/master/src/index.js#L374) from `master` is outside the `if` block in the source code from the `v1.9.2` [release](https://github.com/MatteoGioioso/serverless-pg/blob/v1.9.2/src/index.js#L402).
The client is unusable every time an error gets returned by postgres because of that line being misplaced in the release code.
Could you perhaps release a new version from master? It's causing me a lot of trouble :cry:

**Comment by MatteoGioioso** [comment]
Sorry, I am not quite sure I have understood the problem. 
I think you are confusing the `.connect` with the `.query` method.

**Comment by brapifra** [comment]
Ohhh sorry! I misread it.
In that case, I think the `.query` method should behave as the `.connect` one. `this._client = null` should be inside the if block, otherwise the client becomes unusable whenever a query fails @MatteoGioioso

**Comment by MatteoGioioso** [comment]
Oh, I think you are right, I will check it once more and maybe a fix ASAP

**Comment by MatteoGioioso** [comment]
@brapifra I have pushed a fix, thanks

**Comment by brapifra** [comment]
Thank you @MatteoGioioso
