### ISSUE TITLE
Connection reused when update config object

### ISSUE THREAD

**Issue by TranToan2910** [MatteoGioioso/serverless-pg#49]
Hi, 
I have a lambda function that connects to different databases depending on input parameters.
When I change the input parameter, the result return is still from the previous database.
Current behavior seems to always cached the client object even if the config is updated.

**Comment by MatteoGioioso** [comment]
I see, I might not have considered this use case, could you please post a sample code?
Just to have an idea on how I can implement it.

Thanks

**Comment by TranToan2910** [comment]
My lambda looks something like this, for each customer, we create a database with the same schema.

```
const client = new ServerlessClient({});

const SECRET_ID = process.env.SECRET_ID || '';

export async function handler(event: any, context: any, callback: any): Promise<any> {
  const customerMngService = new CustomerMngService();
  let customer = await customerMngService.get(event.customer_id);
  const dbConfig = await utils.getRDSConnection(SECRET_ID);
  try {
    client.setConfig({
      host: dbConfig.host,
      port: dbConfig.port,
      database: customer.database,
      user: dbConfig.user,
      password: dbConfig.password
    });
    await client.connect();
    // do some logic
  } finally {
    await client.clean();
  }
}
```
When I change the input customer_id, it still returns the query result from the previous customer's database.
Here is how I hack it.

```
// pg-util.ts
export async function connectClient(client: any, config: any) {
    if (isExistConfig(client._config) && isDifferentConfig(client._config, config)) {
        console.log('found different configure. Reset connection');
        // await client.end(); => will cause error Client was closed and is not queryable
        client._client = null;
    }
    client.setConfig(config);
    await client.connect();
}

// then in lambda.ts
// ...
try {
    await connectClient(client, {
      host: dbConfig.host,
      port: dbConfig.port,
      database: customer.database,
      user: dbConfig.user,
      password: dbConfig.password
    });
// continue process
```
 I'm not experienced in this field so it may not be a good solution, but it seems to works.

**Comment by MatteoGioioso** [comment]
ok, thanks, I will try to tackle this next weekend.

**Comment by MatteoGioioso** [comment]
I think this feature will also help who is using IAM authentication

**Comment by MatteoGioioso** [comment]
@TranToan2910 could you please check and let me know?

You should enabled this property.

```
const client = new ServerlessClient({
    allowCredentialsDiffing: true
});
```

**Comment by TranToan2910** [comment]
@MatteoGioioso Great work. Sorry, I was busy with other work. I will check it next week.
