### ISSUE TITLE
manualMaxConnections is type number or Boolean

### ISSUE THREAD

**Issue by hardikpatel5490** [MatteoGioioso/serverless-pg#56]
I want to set manualMaxConnections but I see ambiguity 

manualMaxConnections should be a number But document says different.

Readme says:
![image](https://user-images.githubusercontent.com/78523317/139808378-2dc3186a-81cd-497a-b7b0-d5604a95c4f3.png)

I am trying to set  like this as per document :

        const maxConnections = 10;
        const manualMaxConnections = true;
        this.serverlessClient.setConfig({user, password, maxConnections, manualMaxConnections})

AND ITS NOT ALLOWED as index.d.ts says

![image](https://user-images.githubusercontent.com/78523317/139807999-295cb768-4fad-4d0c-be25-34cd13b8a7de.png)

**Comment by MatteoGioioso** [comment]
I see, let me push a fix over the weekend, thanks.

**Comment by MatteoGioioso** [comment]
Sorry for being late, I have pushed a fix, it should be ok in `v1.9.8`.
