### ISSUE TITLE
SQL Injection

### ISSUE THREAD

**Issue by jamesmart77** [MatteoGioioso/serverless-pg#77]
Sorry, but more of a question here since there wasn't a "general" forum. Since this library depends on `pg`, does it protect against sql injection? If so, would that be formatted the same way it is in that library for [parameterized queries](https://node-postgres.com/features/queries#:~:text=If%20you%20are%20passing%20parameters)?

**Comment by MatteoGioioso** [comment]
Hello, yes, the `.query` method behave almost the same as in node-pg: https://github.com/MatteoGioioso/serverless-pg/blob/4cc2007bfb8aed78280e703e4cc34e9e47236faa/src/index.js#L436
