### ISSUE TITLE
Redshift Compatibility - pg_stat_activity

### ISSUE THREAD

**Issue by adamprescott** [MatteoGioioso/serverless-pg#79]
Hi,
Currently looking at using this library to also connect to Redshift from Lambda, Redshift is wire compatible with Postgres though a few of the system tables have slightly different and missing columns compared to what this library expects, AWS also add other tables which can be used to infer idle sessions.

If no one else is considering this, or working on it, I'm happy to add a PR for this feature/enhancement.

Mainly pg_stat_activity doesn't have all the columns this library expects and there are different ways to identify idle sessions in Redshift.

**Comment by MatteoGioioso** [comment]
Hello, interesting feature, but it may require a bit of refactoring first. 
I never used Redshift, could you please show me what is your plan so I can have an idea? Thanks

**Comment by adamprescott** [comment]
Sure here are a few things I've identified:
* Redshift Clusters have a hard 500 connections limit (despite what's in `pg_database_info`) - though there are mitigations around this via other tooling.
* Can infer if we're connecting to a Redshift DB by running `select version()` and seeing if `.includes('Redshift')`
* `pg_stat_activity` looks slightly different in Redshift, with columns `datid, datname, procpid, usesysid, usename, current_query, query_start` current_query and query_start aren't usually populated unless configured on. We're also missing `application_name`
* `pg_terminate_backend` is a valid means of killing idle sessions
* Redshit has various other tables containing connection, session, and query information

Example query for identifying idle connections, the main issue with this query is it can take:
```sql
with sessions as (SELECT starttime, process, u.usesysid, user_name
        FROM stv_sessions s, pg_user u
        WHERE s.user_name = u.usename
        AND u.usesysid>1
        AND process NOT IN (
            SELECT pid FROM stv_inflight WHERE userid>1
            UNION SELECT pid FROM stv_recents WHERE status != 'Done' AND userid>1
        )), queries as (
            SELECT userid, pid, max(endtime) AS last_end FROM svl_statementtext
            WHERE userid>1 AND sequence=0
            GROUP BY 1,2)

SELECT
    sessions.process AS pid,
    trim(sessions.user_name) AS user_name,
    sessions.starttime AS session_start_time,
    datediff(s, sessions.starttime, sysdate) AS session_duration_is_seconds,
    queries.last_end AS last_query_end_time,
    datediff(s, CASE WHEN queries.last_end IS NOT NULL
        THEN queries.last_end
        ELSE sessions.starttime END
    , sysdate) AS idle_duration_in_seconds
FROM sessions
        LEFT OUTER JOIN queries
            ON sessions.usesysid = queries.userid AND sessions.process = queries.pid
        WHERE (queries.last_end > sessions.starttime OR queries.last_end IS NULL)
        ORDER BY idle_duration_in_seconds DESC;
```

## Implementation
I think there are two viable options:
1. Fork the repo as a new `serverless-redshift` project and make the changes needed to the queries
2. Rework the Strategy into a plugin based approach initially covering Postgres and Redshift but could be later extended by others to include, Google Cloud Spanner, CockroachDB, YugabyteDB, etc...

**Comment by MatteoGioioso** [comment]
Ok, I think we could proceed with the option 2. I will try to assess the viability of abstracting the queries, if it is too complex or tedious we can proceed with the first option.

> Can infer if we're connecting to a Redshift DB by running select version() and seeing if .includes('Redshift')

I guess for this we could just add another option on the config, for example `compatibility: 'Redshift'`.

**Comment by MatteoGioioso** [comment]
@adamprescott I have made a draft PR, please take a look at it: https://github.com/MatteoGioioso/serverless-pg/pull/81

This is the proposed interface:

```
declare interface Plugin {
  getIdleProcessesListByMinimumTimeout(self: ServerlessClient): PluginReturnValue
  getIdleProcessesListOrderByDate(self: ServerlessClient): PluginReturnValue
  processCount(self: ServerlessClient): PluginReturnValue
  killProcesses(self: ServerlessClient, pids: string[]): PluginReturnValue
  showMaxConnections(self: ServerlessClient): PluginReturnValue
}

declare type PluginReturnValue = string | string[] []
```

The return value is an array containing the query and the parameters so that it can be easily supply it to the `.query` method, ex:

```
const result = await this._client.query(...this._plugin.getIdleProcessesListByMinimumTimeout(this))
```

this way you have complete freedom in what parameters you would like to give to your query.

Let me know what you think, Thanks!
