### ISSUE TITLE
Pooling, multiple DB's and high utilisation

### ISSUE THREAD

**Issue by ZacBridge** [MatteoGioioso/serverless-pg#82]
Hi,

PG 13.4 hosted in AWS Aurora DB.

We have a number of different DB's/applications on the same cluster, including one DB being utilised by our monorepo of aws lambda functions (couple hundred functions - not all use postgres but a good chunk do
).

We're seeing issues with mass CPU, connection spikes and high waits as a result of it. 

I'm wondering if I can get an explanation on how this package is actually working with the RDS instance to "pool" connections and handle the requests? My current understanding is as follows:

Each initialization of this package in the code has it's own configuration, watches the number of max connections and GC's accordingly. So in our case, each of our lambdas will be bundling up the code, holding their own version of the default config (max connections 100, and utilConnections 80%) and GC'ing idle connections based on that? So, if our cluster has a maximum of 200 connections (example - not actual case), and we have 200 lambdas, that's nX number of connections, and a bunch of CPU processing to run the pg_stat_activity query and basically no spare resource?

TIA 🙏🏿

**Comment by MatteoGioioso** [comment]
Sorry, I didn't quite understand, are you seeing CPU and connection spikes because of this library or you are evaluating it?

This library will get the max connections directly from your cluster configuration, however if you want to improve performance you can set it yourself to avoid the overhead.
When you call `.clear()` it will calculate if you passed the threshold `processCount > maxConns * connUtilization`, in your case it could be `200 > 200 * 0.8`; if you passed that threshold it will list all the candidate processes to be killed using this query:

```
      WITH processes AS (
          SELECT EXTRACT(EPOCH FROM (Now() - state_change)) AS idle_time,
                 pid
          FROM pg_stat_activity
          WHERE usename = $1
            AND datname = $2
            AND state = 'idle'
            AND application_name = $5
      )
      SELECT pid
      FROM processes
      WHERE idle_time > $3
      LIMIT $4
``` 

You can tweak the `idle_time` and how many you want to kill `LIMIT` (default is all).
With v2 I have introduced client filtering with `application_name` so that you may have different configurations for different applications. 

I hope this is clear, if not feel free to ask.

**Comment by ZacBridge** [comment]
Hi @MatteoGioioso 

Thanks for the quick response. 

My company has a (now somewhat legacy) monorepo of lambdas, around 250 of them, of which a decent portion of them talk to the database. Alongside this, there's 5+ node APIs dockerised and horizontally scaled with their own conn pooling in place.

What i'm trying to understand is how the package handles the connections when each lambda is independently bundled and has it's own instance of the package?

Our configuration is as follows:


```
connectingPromise` = new ServerlessClient({
      host: XXX,
      port: XXX,
      database: XXX,
      user: XXXX,
      password: XX,
      debug: false,
      delayMs: 3000,
      maxConnections: 5, //// THIS IS A NEW ADDITION THAT I'M TRIALLING CURRENTLY - THIS WAS PREVIOUSLY 100 (DEFAULT)
    });
```
and is held outside the direct function invocation runtime of the Lambda. So, assuming we have 50 lambdas that interact with the DB and utilise this package, and 999 max concurrency, are we looking at a new connection with each invocation, until the `maxConns * connUtilization` is reached, then it starts to kill idle connections and cycle through?

Basically, all our lambdas are generally pretty heavily utilised from a concurrency perspective, and our other services are being heavily impacted by this. We aren't yet on V2 so I can't use the application-name directly, nor are the other services lambdas as said above. See below screenshots of the primary issue.
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/34629184/201784015-3ec11e7e-95d4-4fb4-b799-2f789c05ac21.png">

<img width="739" alt="image" src="https://user-images.githubusercontent.com/34629184/201784050-0db9a567-8882-4c5f-b854-c7c144b2d8c5.png">

<img width="583" alt="image" src="https://user-images.githubusercontent.com/34629184/201784063-c223c79c-ff2a-45f6-ab9c-1855bdbc91fc.png">

<img width="966" alt="image" src="https://user-images.githubusercontent.com/34629184/201784092-4615b763-d28a-4329-9a93-a1058b6fb9af.png">

<img width="472" alt="image" src="https://user-images.githubusercontent.com/34629184/201784160-06f0beb7-ffb3-425f-833f-681dc7f1f02b.png">

**Comment by ZacBridge** [comment]
I'm investigating RDS Proxy currently, but it's proving problematic for a number of reasons - still trying to get it to play ball 😅 

Any and all help is much appreciated!

**Comment by MatteoGioioso** [comment]
Why are you setting `maxConnections` to 5? That parameters should be set equal to `max_connections` in postgresql. In the case of (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Managing.html#AuroraPostgreSQL.Managing.MaxConnections)[Aurora there is a formula that depends on your instance size]: `LEAST({DBInstanceClassMemory/9531392},5000)`

Maybe the option ` maxConnections` is a bit misleading, but it is not the max connection for each lambda; as I mentioned above is a parameter is coming directly from your cluster. 
This library query your database, so even though each package has its own configuration they are not working independently.

> are we looking at a new connection with each invocation

No, the connection happens every time a new lambda container/process is "spawned" and it is kept until the library or AWS decides to kill that container/process, so each invocation after the first one will re-utilize the connection.

> Alongside this, there's 5+ node APIs dockerised and horizontally scaled

If they are connecting to the same database as your lambdas you should update to v2

**Comment by ZacBridge** [comment]
It was a (clearly naive) attempt at limiting the max number of connections per lambda to 5. So, we're on a large at the minute, which works out at roughly 900 connections.

If I set maxConnections to 900, Isn't it going to take up to 720 of the available connections for itself, as the connUtilization field is set to 80% by default?

What then happens to the rest of the lambdas?

**Comment by MatteoGioioso** [comment]
> It was a (clearly naive) attempt at limiting the max number of connections per lambda to 5

Yes, It is a bit unintuitive, it will actually cause a lot of unneeded queries.

> If I set maxConnections to 900, Isn't it going to take up to 720 of the available connections for itself, as the connUtilization field is set to 80% by default?

No, not really. That depends entirely on your workload, if you have 900 lambdas spawning all at once it is going to take all the connections with or without this package. The `maxConnections` is just there to establish a threshold.

> Just thought; doesn't the package only query the DB for the max connections if you use the manual override? What would you recommend is the ideal config in this situation?

To improve performance I would suggest setting it yourself, just query your cluster `SHOW max_connections` and use that value. 

> Also, does that ideal config change if I utilise RDS Proxying (which I now have working!)

Consider this library as a "cheap" alternative to RDS proxy. Keep in mind that I have never used RDS Proxy, but as my understanding is the AWS version of pgBouncer, which is done specifically to solve the problem that this package is trying to solve. So in practice you shouldn't need to library if you are using RDS Proxy, pgBouncer or similar =)
