### ISSUE TITLE
[Request] Possibility to use pg.Pool instead.

### ISSUE THREAD

**Issue by rafaell-lycan** [MatteoGioioso/serverless-pg#85]
Ciao @MatteoGioioso 

I'd like to request a feature/enhancement to allow using [`pg.Pool`](https://node-postgres.com/apis/pool) instead, just to simplify its usage and avoid cleaning/ending.

It could be simply a property on the constructor that makes usage or `new Pool(...)` instead.

Thanks!

**Comment by MatteoGioioso** [comment]
Hello

Sorry for the late reply.

Yes, it would simply the code I guess, however I am not sure we would have the same level of control over the connections.
I think at some point I came to the conclusion that it was not possible to use it, but I might be mistaken; if you have a plan on how to implement it that would be great. 

Thanks
